# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.6.dev1604091249
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(754, 841)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupbox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox.setObjectName("groupbox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupbox)
        self.gridLayout.setObjectName("gridLayout")
        self.edtOutFilename = QtWidgets.QLineEdit(self.groupbox)
        self.edtOutFilename.setObjectName("edtOutFilename")
        self.gridLayout.addWidget(self.edtOutFilename, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupbox)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.btnSelOutDir = QtWidgets.QPushButton(self.groupbox)
        self.btnSelOutDir.setObjectName("btnSelOutDir")
        self.gridLayout.addWidget(self.btnSelOutDir, 0, 3, 1, 1)
        self.edtOutDir = QtWidgets.QLineEdit(self.groupbox)
        self.edtOutDir.setObjectName("edtOutDir")
        self.gridLayout.addWidget(self.edtOutDir, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupbox)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupbox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupbox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupbox)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupbox)
        self.horizontalGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalGroupBox1 = QtWidgets.QGroupBox(self.horizontalGroupBox)
        self.horizontalGroupBox1.setObjectName("horizontalGroupBox1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.rbtnNormalClass = QtWidgets.QRadioButton(self.horizontalGroupBox1)
        self.rbtnNormalClass.setChecked(True)
        self.rbtnNormalClass.setObjectName("rbtnNormalClass")
        self.horizontalLayout_3.addWidget(self.rbtnNormalClass)
        self.rbtnAbstractClass = QtWidgets.QRadioButton(self.horizontalGroupBox1)
        self.rbtnAbstractClass.setObjectName("rbtnAbstractClass")
        self.horizontalLayout_3.addWidget(self.rbtnAbstractClass)
        self.rbtnInterface = QtWidgets.QRadioButton(self.horizontalGroupBox1)
        self.rbtnInterface.setObjectName("rbtnInterface")
        self.horizontalLayout_3.addWidget(self.rbtnInterface)
        self.verticalLayout_2.addWidget(self.horizontalGroupBox1)
        self.groupbox1 = QtWidgets.QGroupBox(self.horizontalGroupBox)
        self.groupbox1.setObjectName("groupbox1")
        self.formLayout = QtWidgets.QFormLayout(self.groupbox1)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.groupbox1)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.edtReadName = QtWidgets.QLineEdit(self.groupbox1)
        self.edtReadName.setStatusTip("")
        self.edtReadName.setWhatsThis("")
        self.edtReadName.setInputMask("")
        self.edtReadName.setMaxLength(32767)
        self.edtReadName.setDragEnabled(False)
        self.edtReadName.setObjectName("edtReadName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edtReadName)
        self.label_6 = QtWidgets.QLabel(self.groupbox1)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.edtPrefix = QtWidgets.QLineEdit(self.groupbox1)
        self.edtPrefix.setObjectName("edtPrefix")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.edtPrefix)
        self.label_3 = QtWidgets.QLabel(self.groupbox1)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.edtSnakeID = QtWidgets.QLineEdit(self.groupbox1)
        self.edtSnakeID.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edtSnakeID.setObjectName("edtSnakeID")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.edtSnakeID)
        self.label_4 = QtWidgets.QLabel(self.groupbox1)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.edtCamelID = QtWidgets.QLineEdit(self.groupbox1)
        self.edtCamelID.setObjectName("edtCamelID")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.edtCamelID)
        self.label_5 = QtWidgets.QLabel(self.groupbox1)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.edtBigSnakeID = QtWidgets.QLineEdit(self.groupbox1)
        self.edtBigSnakeID.setInputMethodHints(QtCore.Qt.ImhNone)
        self.edtBigSnakeID.setObjectName("edtBigSnakeID")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.edtBigSnakeID)
        self.verticalLayout_2.addWidget(self.groupbox1)
        self.formGroupBox = QtWidgets.QGroupBox(self.horizontalGroupBox)
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout_3 = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.formLayout_3.setObjectName("formLayout_3")
        self.label_12 = QtWidgets.QLabel(self.formGroupBox)
        self.label_12.setObjectName("label_12")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_12)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_16 = QtWidgets.QLabel(self.formGroupBox)
        self.label_16.setObjectName("label_16")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_16)
        self.edtPrefixParent = QtWidgets.QLineEdit(self.formGroupBox)
        self.edtPrefixParent.setObjectName("edtPrefixParent")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.edtPrefixParent)
        self.label_13 = QtWidgets.QLabel(self.formGroupBox)
        self.label_13.setObjectName("label_13")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.label_14 = QtWidgets.QLabel(self.formGroupBox)
        self.label_14.setObjectName("label_14")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formGroupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.verticalLayout_2.addWidget(self.formGroupBox)
        spacerItem = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.formFrame = QtWidgets.QFrame(self.horizontalGroupBox)
        self.formFrame.setObjectName("formFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.formFrame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.formFrame)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lstProperties = QtWidgets.QTableView(self.groupBox)
        self.lstProperties.setStyleSheet("")
        self.lstProperties.setObjectName("lstProperties")
        self.verticalLayout_4.addWidget(self.lstProperties)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.formFrame)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lstSignals = QtWidgets.QTableView(self.groupBox_2)
        self.lstSignals.setObjectName("lstSignals")
        self.verticalLayout_5.addWidget(self.lstSignals)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.formFrame)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lstImplInteface = QtWidgets.QTableView(self.groupBox_3)
        self.lstImplInteface.setObjectName("lstImplInteface")
        self.verticalLayout_6.addWidget(self.lstImplInteface)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_2.addWidget(self.formFrame)
        self.verticalLayout.addWidget(self.horizontalGroupBox)
        self.groupbox2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupbox2.setObjectName("groupbox2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupbox2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton = QtWidgets.QPushButton(self.groupbox2)
        self.pushButton.setAutoDefault(True)
        self.pushButton.setDefault(True)
        self.pushButton.setFlat(False)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.groupbox2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 754, 23))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menuBar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menuBar)
        self.act_open_default_tmpl_dir = QtWidgets.QAction(MainWindow)
        self.act_open_default_tmpl_dir.setObjectName("act_open_default_tmpl_dir")
        self.act_open_user_tmpl_dir = QtWidgets.QAction(MainWindow)
        self.act_open_user_tmpl_dir.setObjectName("act_open_user_tmpl_dir")
        self.act_about_me = QtWidgets.QAction(MainWindow)
        self.act_about_me.setObjectName("act_about_me")
        self.act_help = QtWidgets.QAction(MainWindow)
        self.act_help.setObjectName("act_help")
        self.menu.addAction(self.act_open_default_tmpl_dir)
        self.menu.addAction(self.act_open_user_tmpl_dir)
        self.menu_2.addAction(self.act_help)
        self.menu_2.addAction(self.act_about_me)
        self.menuBar.addAction(self.menu.menuAction())
        self.menuBar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GObject对象生成器 by 谭戬"))
        self.groupbox.setTitle(_translate("MainWindow", "输出信息"))
        self.label_7.setText(_translate("MainWindow", "输出文件名"))
        self.btnSelOutDir.setText(_translate("MainWindow", "选择"))
        self.label.setText(_translate("MainWindow", "输出目录"))
        self.label_9.setText(_translate("MainWindow", "?.c"))
        self.label_8.setText(_translate("MainWindow", "将会生成的文件"))
        self.label_11.setText(_translate("MainWindow", "?.h"))
        self.horizontalGroupBox.setTitle(_translate("MainWindow", "创建信息"))
        self.horizontalGroupBox1.setTitle(_translate("MainWindow", "类型"))
        self.rbtnNormalClass.setText(_translate("MainWindow", "一般类"))
        self.rbtnAbstractClass.setText(_translate("MainWindow", "抽象类"))
        self.rbtnInterface.setText(_translate("MainWindow", "接口类"))
        self.groupbox1.setTitle(_translate("MainWindow", "名称/标识符"))
        self.label_2.setText(_translate("MainWindow", "可读名称"))
        self.edtReadName.setPlaceholderText(_translate("MainWindow", "readable name"))
        self.label_6.setText(_translate("MainWindow", "前缀"))
        self.edtPrefix.setPlaceholderText(_translate("MainWindow", "Prefix"))
        self.label_3.setText(_translate("MainWindow", "蛇形标识符"))
        self.edtSnakeID.setPlaceholderText(_translate("MainWindow", "prefix_readable_name"))
        self.label_4.setText(_translate("MainWindow", "驼峰标识符"))
        self.edtCamelID.setPlaceholderText(_translate("MainWindow", "PrefixReadableName"))
        self.label_5.setText(_translate("MainWindow", "大写蛇形标识符"))
        self.edtBigSnakeID.setPlaceholderText(_translate("MainWindow", "PREFIX_READABLE_NAME"))
        self.formGroupBox.setTitle(_translate("MainWindow", "继承的类"))
        self.label_12.setText(_translate("MainWindow", "类名"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "GObject"))
        self.label_16.setText(_translate("MainWindow", "前缀"))
        self.edtPrefixParent.setPlaceholderText(_translate("MainWindow", "G"))
        self.label_13.setText(_translate("MainWindow", "类结构体名"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "GObjectClass"))
        self.label_14.setText(_translate("MainWindow", "GType函数/宏"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "G_TYPE_OBJECT"))
        self.groupBox.setTitle(_translate("MainWindow", "属性列表"))
        self.groupBox_2.setTitle(_translate("MainWindow", "信号列表"))
        self.groupBox_3.setTitle(_translate("MainWindow", "实现的接口列表"))
        self.lstImplInteface.setToolTip(_translate("MainWindow", "请填写获取GType的表达式/函数/宏!"))
        self.pushButton.setText(_translate("MainWindow", "生成"))
        self.pushButton.setShortcut(_translate("MainWindow", "Return"))
        self.menu.setTitle(_translate("MainWindow", "模版"))
        self.menu_2.setTitle(_translate("MainWindow", "关于"))
        self.act_open_default_tmpl_dir.setText(_translate("MainWindow", "打开默认模版目录"))
        self.act_open_default_tmpl_dir.setShortcut(_translate("MainWindow", "F3"))
        self.act_open_user_tmpl_dir.setText(_translate("MainWindow", "打开用户模版目录"))
        self.act_open_user_tmpl_dir.setShortcut(_translate("MainWindow", "F4"))
        self.act_about_me.setText(_translate("MainWindow", "本软件"))
        self.act_about_me.setShortcut(_translate("MainWindow", "F2"))
        self.act_help.setText(_translate("MainWindow", "帮助"))
        self.act_help.setShortcut(_translate("MainWindow", "F1"))

